### ISSUE TITLE
title attribute does not show hover text in chromium based browsers

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/playground#393]
I have discovered that the mouse overlay does not show a text overlay for the places we have the `title` attribute in Chromium based browsers (Safari too when content blockers are disabled). These are seen in places like OpenAPI and AsyncAPI buttons, validation explanations, download and link buttons

**Comment by hasanheroglu** [comment]
I've tried on Opera and Safari it seems to work. Maybe it depends on the version of the browser?

**Comment by egekorkan** [comment]
I have just tried it on Linux Chrome and it works but when I have created the issue I was testing on Chrome on MacOS. @hasanheroglu which OS do you use?

**Comment by hasanheroglu** [comment]
I'm on MacOS right now.

**Comment by egekorkan** [comment]
This is unrelated now with the new web package, closing.
