### ISSUE TITLE
Cloudflare and jsdeliver are detected as trackers in Safari browser

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/playground#394]
When opening playground in Safari, an unusable page opens since all our dependencies from cloudflare and jsdeliver are recognized as trackers. Ghostery extension in Firefox and Chrome does not detect them as trackers. This is really annoying since disabling these content blockers is not very intuitive. You cannot do it from the trackers page but you should go to a site specific settings page and disable content blockers for Playground.

We cannot be the only one using Cloudflare for fetching the dependencies so there must be a solution to allow safari to whitelist this. 

@hasanheroglu do you have a MacOs and Safari Browser to investigate the problem?

**Comment by hasanheroglu** [comment]
@egekorkan Yes, I do.

**Comment by egekorkan** [comment]
Not an issue after redesign
