### ISSUE TITLE
Detecting protocols for AID generation

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/playground#507]
The current AID generator hardcodes http and coap at [this line](https://github.com/eclipse-thingweb/playground/blob/679848e14aea288f8d4daa1836f31d54082c9a32/packages/web-new/src/scripts/util.js#L175). It should first detect the protocol and use the appropriate one.

**Comment by danielpeintner** [comment]
Note: I think in the case  of the playground the 2nd parameter should be omitted and the tool will figure out all available bindings itself.

`const AASInstance = assetInterfaceDescriptionUtil.transformTD2SM(tdToConvert, ["http", "coap"])`
-->
`const AASInstance = assetInterfaceDescriptionUtil.transformTD2SM(tdToConvert)`
