### ISSUE TITLE
[web-new] CSS mapping file

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/playground#545]
Thanks for resolving the conflicts. I think the map file should be removed in another PR. Are you sure it is not needed though?

_Originally posted by @egekorkan in https://github.com/eclipse-thingweb/playground/issues/537#issuecomment-1849001305_

**Comment by SergioCasCeb** [comment]
Yeah, I am sure that it is not needed as only the vs extension uses it to create the CSS file. And the application itself technically only needs the CSS, so technically even the SASS files could be removed

**Comment by egekorkan** [comment]
In this case, we should put this step into the build process via Webpack so that we guarantee the correctness of the CSS files.

**Comment by egekorkan** [comment]
This is done via #547
