### ISSUE TITLE
Collapse/Open icons are reversed

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/playground#557]
In the following screenshot, the small arrows should be reversed:

![image](https://github.com/eclipse-thingweb/playground/assets/20195407/ac9b2605-5d4f-4513-9c7f-12f05c81ec23)

`>` should mean not opened, `v` should mean opened

**Comment by SergioCasCeb** [comment]
Thank you for pointing that out, i will fix it with the current PR of the SVG icons
