### ISSUE TITLE
Deleting tools and adjusting dependencies to use new @thingweb packages

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/playground#586]
With new locations for our dependencies at the following locations, we can adjust the repo and dependencies to use the new locations:

- https://www.npmjs.com/package/@thingweb/thing-model
- https://www.npmjs.com/package/@thingweb/open-api-converter
- https://www.npmjs.com/package/@thingweb/json-spell-checker

**Comment by hasanheroglu** [comment]
I will handle this.
